sudo: false
services: mongodb

notifications:
  email: false

language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3

gemfile:
  - Gemfile
  - gemfiles/carrierwave-0.10.gemfile
  - gemfiles/carrierwave-0.11.gemfile
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/mongoid-5.0.gemfile
  - gemfiles/mongoid-6.0.gemfile

matrix:
  fast_finish: true
